package com.cijene.sdk.models.zip;

import lombok.Data;

import java.time.LocalDate;
import java.time.ZonedDateTime;

/**
 * Represents a downloadable ZIP archive of scraped price data.
 * <p>
 * Each archive corresponds to a specific snapshot of the dataset
 * generated by the data ingestion pipeline.
 */
@Data
public class ZipArchive {

    /** Date of the dataset snapshot contained in the archive. */
    private LocalDate date;

    /** Direct download URL for the ZIP archive. */
    private String url;

    /** Size of the archive in bytes. */
    private Integer size;

    /** Timestamp when the archive was last updated or generated. */
    private ZonedDateTime updated;
}
